version: "3.8"
services:
  ftpd:
    build:
      context: .
      dockerfile: ./ftp/ftpd/Dockerfile
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - /camera:/root
    restart: always

  ftp_push_config:
    build:
      context: .
      dockerfile: ./ftp/push_config/Dockerfile
    environment:
      - CONCIERGE_IP_ADDRESS
    restart: always

