version: "3.8"
services:
  grafana:
    image: grafana/grafana:7.3.0
    ports:
      - "3000:3000"

  influx:
    build:
      context: .
      dockerfile: ./influx/Dockerfile
      args:
        - FLASK=$VERSION_FLASK
        - FLASK_RESTFUL=$VERSION_FLASK_RESTFUL
    ports:
      - "8086:8086"
      - "8083:8083"
    environment:
      - CONCIERGE_IP_ADDRESS
      - INFLUXDB_ADMIN_ENABLED
    volumes:
      - /camera/influx:/data
    restart: always
