version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "80:8080"
    environment:
      - CONCIERGE_IP_ADDRESS
    volumes:
      - /${ROOT_DIR}:/root
    restart: always

networks:
  cinternal:
    internal: true
