# Generated by Django 3.1.3 on 2020-11-18 13:10

from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Brussels')),
                ('live_url_hd', models.CharField(blank=True, max_length=512)),
                ('live_url_sd', models.CharField(blank=True, max_length=512)),
                ('snapshot_url', models.CharField(blank=True, max_length=512)),
                ('live_matrix_position', models.IntegerField(default=0, help_text='display position live feed')),
                ('live_hdmi_port', models.IntegerField(default=99, help_text='output port (99 is none)')),
                ('last_recording_matrix_position', models.IntegerField(default=0, help_text='display position live feed')),
                ('last_recording_hdmi_port', models.IntegerField(default=99, help_text='output port (99 is none)')),
            ],
        ),
        migrations.CreateModel(
            name='CameraBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraListeners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=255)),
                ('recording_date_time', models.DateTimeField()),
                ('duration', models.FloatField(help_text='duration of recording in seconds')),
                ('nbr_frames', models.IntegerField(help_text='number of video frames')),
                ('resolution', models.CharField(max_length=64)),
                ('processed_by_analytics', models.BooleanField(default=False)),
                ('low_res_file_path', models.CharField(blank=True, max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camerabrand')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.cameratype'),
        ),
        migrations.AddField(
            model_name='camera',
            name='services',
            field=models.ManyToManyField(blank=True, to='camera.CameraServices'),
        ),
    ]
