# Generated by Django 3.1.3 on 2020-11-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralisteners',
            name='callback_type',
            field=models.CharField(default='ftp', max_length=32),
        ),
    ]
