# Generated by Django 3.1.3 on 2020-11-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_cameralisteners_callback_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_type', to='camera.cameratype'),
        ),
    ]
