# Generated by Django 3.1.3 on 2020-12-04 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20201204_0627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='services',
            new_name='analytics_profile',
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 6, 34, 53, 966194)),
        ),
    ]
