# Generated by Django 3.1.3 on 2020-11-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20201123_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='state',
            field=models.CharField(default='NOK', max_length=16),
        ),
    ]
