# Generated by Django 3.1.3 on 2020-12-04 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_auto_20201204_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsprofile',
            name='min_nbr_video_frames_skipped',
            field=models.IntegerField(default=60, help_text='maximum number of frames skipped during video analytics'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 7, 57, 57, 341094)),
        ),
    ]
