# Generated by Django 3.1.3 on 2020-11-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20201126_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
