# Generated by Django 3.1.3 on 2020-11-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_auto_20201126_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='duration',
            field=models.FloatField(blank=True, help_text='duration of recording in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='nbr_frames',
            field=models.IntegerField(blank=True, help_text='number of video frames', null=True),
        ),
    ]
