# Generated by Django 3.1.4 on 2020-12-23 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_auto_20201223_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='knownobjects',
            name='deep_learning_done',
            field=models.BooleanField(default=False, help_text='Set to True if deep learing processing is finished'),
        ),
        migrations.AlterField(
            model_name='knownobjects',
            name='file_path_image',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 10, 9, 45, 141550)),
        ),
    ]
