# Generated by Django 3.1.3 on 2020-11-28 18:53

import camera.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[camera.models.validate_not_underscore])),
                ('host', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Brussels')),
                ('live_url_hd', models.CharField(blank=True, max_length=512)),
                ('live_url_sd', models.CharField(blank=True, max_length=512)),
                ('snapshot_url', models.CharField(blank=True, max_length=512)),
                ('live_matrix_position', models.IntegerField(default=0, help_text='display position live feed')),
                ('live_hdmi_port', models.IntegerField(default=99, help_text='output port (99 is none)')),
                ('last_recording_matrix_position', models.IntegerField(default=0, help_text='display position live feed')),
                ('last_recording_hdmi_port', models.IntegerField(default=99, help_text='output port (99 is none)')),
                ('state', models.CharField(default='NOK', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CameraBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraListeners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('callback_type', models.CharField(default='ftp', max_length=32)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CameraServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path_video', models.CharField(blank=True, max_length=512)),
                ('file_path_snapshot', models.CharField(blank=True, max_length=512)),
                ('recording_date_time', models.DateTimeField(default=datetime.datetime(2020, 11, 28, 18, 53, 50, 780493))),
                ('duration', models.FloatField(blank=True, help_text='duration of recording in seconds', null=True)),
                ('nbr_frames', models.IntegerField(blank=True, help_text='number of video frames', null=True)),
                ('resolution', models.CharField(blank=True, max_length=64)),
                ('video_processed_by_analytics', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camera')),
            ],
        ),
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.camerabrand')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_type', to='camera.cameratype'),
        ),
        migrations.AddField(
            model_name='camera',
            name='services',
            field=models.ManyToManyField(blank=True, to='camera.CameraServices'),
        ),
    ]
