# Generated by Django 3.1.3 on 2020-12-04 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0006_auto_20201204_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='url_snapshot',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='url_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='url_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 4, 11, 23, 11, 432768)),
        ),
    ]
