# Generated by Django 3.1.4 on 2020-12-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0007_auto_20201204_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='file_path_video',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 18, 0, 32, 140145)),
        ),
    ]
