# Generated by Django 3.1.4 on 2020-12-11 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0008_auto_20201208_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_date_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 11, 44, 27, 686191)),
        ),
    ]
